Lambda School Data Science

*Unit 2, Sprint 3, Module 1*

---


# Define ML problems

You will use your portfolio project dataset for all assignments this sprint.

## Assignment

Complete these tasks for your project, and document your decisions.

- [ ] Choose your target. Which column in your tabular dataset will you predict?
- [ ] Is your problem regression or classification?
- [ ] How is your target distributed?
    - Classification: How many classes? Are the classes imbalanced?
    - Regression: Is the target right-skewed? If so, you may want to log transform the target.
- [ ] Choose your evaluation metric(s).
    - Classification: Is your majority class frequency >= 50% and < 70% ? If so, you can just use accuracy if you want. Outside that range, accuracy could be misleading. What evaluation metric will you choose, in addition to or instead of accuracy?
    - Regression: Will you use mean absolute error, root mean squared error, R^2, or other regression metrics?
- [ ] Choose which observations you will use to train, validate, and test your model.
    - Are some observations outliers? Will you exclude them?
    - Will you do a random split or a time-based split?
- [ ] Begin to clean and explore your data.
- [ ] Begin to choose which features, if any, to exclude. Would some features "leak" future information?

If you haven't found a dataset yet, do that today. [Review requirements for your portfolio project](https://lambdaschool.github.io/ds/unit2) and choose your dataset.

Some students worry, ***what if my model isn't “good”?*** Then, [produce a detailed tribute to your wrongness. That is science!](https://twitter.com/nathanwpyle/status/1176860147223867393)

In [ ]:
#My target is my fantasy rank position.
#My problem is regression.
#Right Skewed
#I will use MAE,RMSE,R^2, and other regression metrics.
#I will do a time split
    #train = 2015 and before
    #test = 2016 and after
    #val = 2014-2015

In [42]:
import pandas as pd
df = pd.read_csv('C:/Users/Jake/Jake_Dennis_DS-Unit-2-Applied-Modeling/data/fantasy3.csv')
print(df.shape)
df.head()

(6672, 26)

,Year,Name,Tm,FantPos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,...,Rec_Tgt,Rec,Rec_Yds,Rec_Y/R,Rec_TD,FantPt,PPR,PPG,PPRPG,PosRank
0,2008,Drew Brees,NOR,QB,29.0,16.0,16.0,413.0,635.0,5069.0,...,0.0,0.0,0.0,NaN,0.0,305.0,305.0,19.0625,19.0625,1.0
1,2008,Aaron Rodgers,GNB,QB,25.0,16.0,16.0,341.0,536.0,4038.0,...,0.0,0.0,0.0,NaN,0.0,296.0,296.0,18.5,18.5,2.0
2,2008,Philip Rivers,SDG,QB,27.0,16.0,16.0,312.0,478.0,4009.0,...,0.0,0.0,0.0,NaN,0.0,287.0,287.0,17.9375,17.9375,3.0
3,2008,DeAngelo Williams,CAR,RB,25.0,16.0,16.0,0.0,0.0,0.0,...,30.0,22.0,121.0,5.5,2.0,286.0,308.0,17.875,19.25,1.0
4,2008,Jay Cutler,DEN,QB,25.0,16.0,16.0,384.0,616.0,4526.0,...,0.0,0.0,0.0,NaN,0.0,281.0,281.0,17.5625,17.5625,4.0

In [14]:
df.isnull().sum()

Year           0
Name           0
Tm             0
FantPos      796
Age            3
G             98
GS           241
Pass_Cmp       1
Pass_Att       1
Pass_Yds       1
Pass_TD        1
Int            1
Rush_Att       1
Rush_Yds       1
Rush_Y/A    3326
Rush_TD        1
Rec_Tgt      419
Rec            1
Rec_Yds        1
Rec_Y/R     1715
Rec_TD         1
FantPt       953
PPR          775
PPG            0
PPRPG        622
PosRank      622
dtype: int64

In [43]:
df = df.dropna(subset=['PosRank', 'Rec', 'FantPos'])
print(df.shape)
df.isnull().sum()

(5321, 26)

Year           0
Name           0
Tm             0
FantPos        0
Age            2
G              0
GS             0
Pass_Cmp       0
Pass_Att       0
Pass_Yds       0
Pass_TD        0
Int            0
Rush_Att       0
Rush_Yds       0
Rush_Y/A    2304
Rush_TD        0
Rec_Tgt        5
Rec            0
Rec_Yds        0
Rec_Y/R      851
Rec_TD         0
FantPt       161
PPR           44
PPG            0
PPRPG          0
PosRank        0
dtype: int64

In [44]:
train = df[df['Year'] < 2016]
test = df[df['Year'] > 2015]
val = train[train['Year'] > 2013]

In [56]:
import numpy as np
target = ['PosRank']
drop = ['Year', 'Name', 'PosRank']
X_train = train.drop(columns=drop)
y_train = train[target]
X_val = val.drop(columns=drop)
y_val = val[target]
X_test = test.drop(columns=drop)

In [50]:
print(y_train.shape)
X_train.shape

(4229, 1)

(4229, 23)

In [65]:
X_test.head()

,Tm,FantPos,Age,G,GS,Pass_Cmp,Pass_Att,Pass_Yds,Pass_TD,Int,...,Rush_TD,Rec_Tgt,Rec,Rec_Yds,Rec_Y/R,Rec_TD,FantPt,PPR,PPG,PPRPG
4894,KAN,WR,24.0,16.0,5.0,0.0,0.0,0.0,0.0,0.0,...,1.0,51.0,31.0,279.0,9.00,2.0,51.0,82.0,3.1875,5.125
4895,HOU,RB,25.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,16.0,12.0,40.0,3.33,0.0,50.0,62.0,3.571428571,4.428571429
4896,CLE,WR,30.0,16.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,54.0,33.0,324.0,9.82,3.0,50.0,83.0,3.125,5.1875
4897,TAM,RB,31.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,6.0,77.0,12.83,0.0,10.0,16.0,3.333333333,5.333333333
4898,MIA,RB,30.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,10.0,6.0,78.0,13.00,0.0,13.0,19.0,3.25,4.75

In [48]:
!pip install category_encoders==2.*

Collecting category_encoders==2.*
  Downloading category_encoders-2.1.0-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: scipy>=0.19.0 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (1.4.1)
Requirement already satisfied: numpy>=1.11.3 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (1.18.1)
Requirement already satisfied: patsy>=0.4.1 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (0.5.1)
Requirement already satisfied: statsmodels>=0.6.1 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (0.11.0)
Requirement already satisfied: pandas>=0.21.1 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (1.0.1)
Requirement already satisfied: scikit-learn>=0.20.0 in e:\anaconda\lib\site-packages (from category_encoders==2.*) (0.22.1)
Requirement already satisfied: six in e:\anaconda\lib\site-packages (from patsy>=0.4.1->category_encoders==2.*) (1.14.0)
Requirement already satisfied: python-dateutil>=2.6.1 in e:\anaconda\lib\site-packages (from pandas>=0.21.1->category_encoders==2.*) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in e:\anaconda\lib\site-packages (from pandas>=0.21.1->category_encoders==2.*) (2019.3)
Requirement already satisfied: joblib>=0.11 in e:\anaconda\lib\site-packages (from scikit-learn>=0.20.0->category_encoders==2.*) (0.14.1)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.1.0

In [54]:
import category_encoders as ce
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from scipy.stats import randint, uniform
from sklearn.model_selection import RandomizedSearchCV

pipeline = make_pipeline(
    ce.TargetEncoder(), 
    SimpleImputer(), 
    RandomForestRegressor(random_state=42)
)

pipeline.fit(X_train, y_train.values.ravel())
print ('Validation Accuracy', pipeline.score(X_val, y_val))

Validation Accuracy 0.9966047577117039

In [63]:
test_pred = pipeline.predict(X_test)

In [58]:
print(pipeline.score(X_test, test_pred))

1.0

In [64]:
testdf = pd.DataFrame(test_pred)
testdf.head()

        0
0   84.19
1   66.52
2   85.93
3  117.66
4  110.64

In [62]:
y_train.head()

   PosRank
0      1.0
1      2.0
2      3.0
3      1.0
4      4.0

In [ ]:
#Not sure whats wrong with it at the moment but I'll explore the data more tomorrow